ALTER TABLE `flink_ecosystem`.`package` 
CHANGE COLUMN `slug` `slug` VARCHAR(255) CHARACTER SET 'utf8' NOT NULL DEFAULT '' ,
CHANGE COLUMN `name` `name` VARCHAR(255) CHARACTER SET 'utf8' NOT NULL DEFAULT '' ,
CHANGE COLUMN `description` `description` LONGTEXT CHARACTER SET 'utf8' NOT NULL ,
CHANGE COLUMN `readme` `readme` LONGTEXT CHARACTER SET 'utf8' NOT NULL ,
CHANGE COLUMN `website` `website` VARCHAR(255) CHARACTER SET 'utf8' NOT NULL DEFAULT '' ,
CHANGE COLUMN `repository` `repository` VARCHAR(255) CHARACTER SET 'utf8' NOT NULL DEFAULT '' ,
CHANGE COLUMN `license` `license` VARCHAR(255) CHARACTER SET 'utf8' NOT NULL DEFAULT '' ,
CHANGE COLUMN `category` `category` VARCHAR(255) CHARACTER SET 'utf8' NOT NULL DEFAULT '' ,
CHANGE COLUMN `tags` `tags` VARCHAR(255) CHARACTER SET 'utf8' NULL DEFAULT '' ;

ALTER TABLE `flink_ecosystem`.`comment` 
CHANGE COLUMN `text` `text` LONGTEXT CHARACTER SET 'utf8' NOT NULL ;